// src/utils/mockItinerary.ts
import {
  TripItinerary,
  PriceLevel,
  WarningSeverity,
  PermissionType,
  VoteType,
} from '@/src/types/destinations';

// Mock data for trip itinerary
export const parisItinerary: TripItinerary = {
  id: 'mock-itinerary-123',
  title: 'Exploring Paris',
  description: 'A week-long adventure through the city of lights',
  image_url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34',
  total_cost: 1200,
  currency: 'EUR',
  user_id: 'user-123',
  start_date: '2025-06-15',
  end_date: '2025-06-22',
  created_at: '2025-04-20T10:30:00Z',
  updated_at: '2025-04-25T14:15:00Z',
  city: 'Paris',
  location: 'France',
  tags: ['romantic', 'historic', 'culinary'],
  rating: 4.8,
  price_level: PriceLevel.Moderate,
  coordinates: {
    lat: 48.856614,
    lng: 2.3522219,
  },
  is_featured: true,
  category: 'city',
  is_bookmarked: false,
  is_shared: true,
  is_public: true,
  is_private: false,
  is_completed: true,
  is_favorite: false,

  // Weather information
  weather: [
    {
      id: 'weather-1',
      itinerary_id: 'mock-itinerary-123',
      day: 1,
      date: '2025-06-15',
      condition: 'Sunny',
      high_temp: 25,
      low_temp: 16,
      icon: 'weather-sunny',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'weather-2',
      itinerary_id: 'mock-itinerary-123',
      day: 2,
      date: '2025-06-16',
      condition: 'Partly Cloudy',
      high_temp: 24,
      low_temp: 15,
      icon: 'weather-partly-cloudy',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'weather-3',
      itinerary_id: 'mock-itinerary-123',
      day: 3,
      date: '2025-06-17',
      condition: 'Light Rain',
      high_temp: 21,
      low_temp: 14,
      icon: 'weather-rainy',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'weather-4',
      itinerary_id: 'mock-itinerary-123',
      day: 4,
      date: '2025-06-18',
      condition: 'Sunny',
      high_temp: 23,
      low_temp: 15,
      icon: 'weather-sunny',
      created_at: '2025-04-20T10:30:00Z',
    },
  ],

  weather_overview: {
    id: 'weather-overview-1',
    itinerary_id: 'mock-itinerary-123',
    description:
      'Paris will be mostly warm and pleasant during your visit, with occasional light showers. Pack a light jacket and umbrella just in case.',
    recommendations: [
      {
        id: 'weather-rec-1',
        weather_overview_id: 'weather-overview-1',
        text: 'Pack a lightweight raincoat',
        icon: 'umbrella',
        created_at: '2025-04-20T10:30:00Z',
      },
      {
        id: 'weather-rec-2',
        weather_overview_id: 'weather-overview-1',
        text: 'Sunscreen for sunny days',
        icon: 'weather-sunny-alert',
        created_at: '2025-04-20T10:30:00Z',
      },
      {
        id: 'weather-rec-3',
        weather_overview_id: 'weather-overview-1',
        text: 'Comfortable walking shoes',
        icon: 'shoe-sneaker',
        created_at: '2025-04-20T10:30:00Z',
      },
    ],
    created_at: '2025-04-20T10:30:00Z',
  },

  // Warnings
  warnings: [
    {
      id: 'warning-1',
      itinerary_id: 'mock-itinerary-123',
      title: 'Pickpocketing',
      description:
        'Be aware of pickpockets in tourist areas, especially around the Eiffel Tower and on public transport.',
      severity: WarningSeverity.Medium,
      icon: 'alert',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'warning-2',
      itinerary_id: 'mock-itinerary-123',
      title: 'Tourist Scams',
      description:
        'Watch out for common scams like the bracelet scam or petition signers near major attractions.',
      severity: WarningSeverity.Low,
      icon: 'information-outline',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'warning-3',
      itinerary_id: 'mock-itinerary-123',
      title: 'Metro Strikes',
      description:
        'Occasional transport strikes may affect travel plans. Check local news for updates.',
      severity: WarningSeverity.Low,
      icon: 'train',
      created_at: '2025-04-20T10:30:00Z',
    },
  ],

  // Packing recommendations
  packing_recommendation: [
    {
      id: 'packing-1',
      itinerary_id: 'mock-itinerary-123',
      name: 'Universal travel adapter',
      category: 'electronics',
      essential: true,
      icon: 'power-plug',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'packing-2',
      itinerary_id: 'mock-itinerary-123',
      name: 'Comfortable walking shoes',
      category: 'clothing',
      essential: true,
      icon: 'shoe-sneaker',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'packing-3',
      itinerary_id: 'mock-itinerary-123',
      name: 'Lightweight rain jacket',
      category: 'clothing',
      essential: false,
      icon: 'umbrella',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'packing-4',
      itinerary_id: 'mock-itinerary-123',
      name: 'Camera',
      category: 'electronics',
      essential: false,
      icon: 'camera',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'packing-5',
      itinerary_id: 'mock-itinerary-123',
      name: 'French phrasebook',
      category: 'miscellaneous',
      essential: false,
      icon: 'book',
      created_at: '2025-04-20T10:30:00Z',
    },
  ],

  // General tips
  general_tips: [
    {
      id: 'tip-1',
      itinerary_id: 'mock-itinerary-123',
      title: 'Learn basic French phrases',
      description: 'Parisians appreciate visitors who make an effort to speak some French.',
      icon: 'chat',
      category: 'culture',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'tip-2',
      itinerary_id: 'mock-itinerary-123',
      title: 'Museum Pass',
      description:
        'Consider buying a Paris Museum Pass for free entry to over 60 museums and monuments.',
      icon: 'ticket',
      category: 'savings',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'tip-3',
      itinerary_id: 'mock-itinerary-123',
      title: 'Metro Navigation',
      description:
        'The Paris Metro is extensive and efficient. Download the RATP app for easy navigation.',
      icon: 'subway',
      category: 'transport',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'tip-4',
      itinerary_id: 'mock-itinerary-123',
      title: 'Tipping Culture',
      description:
        'Service is usually included in restaurant bills, but leaving a small tip is appreciated.',
      icon: 'currency-eur',
      category: 'culture',
      created_at: '2025-04-20T10:30:00Z',
    },
  ],

  // Trip highlights
  trip_highlights: [
    {
      id: 'highlight-1',
      itinerary_id: 'mock-itinerary-123',
      title: 'Eiffel Tower',
      description: 'Visit the iconic Eiffel Tower, preferably at sunset for spectacular views.',
      icon: 'tower',
      created_at: '2025-04-20T10:30:00Z',
    },
    {
      id: 'highlight-2',
      itinerary_id: 'mock-itinerary-123',
      title: 'Louvre Museum',
      description: 'Home to thousands of works of art including the Mona Lisa.',
      icon: 'museum',
      created_at: '2025-04-20T10:30:00Z',
    },
  ],

  // Days and activities
  days: [
    {
      id: 'day-1',
      itinerary_id: 'mock-itinerary-123',
      day_number: 1,
      date: '2025-06-15',
      created_at: '2025-04-20T10:30:00Z',
      activities: [
        {
          id: 'activity-1',
          day_id: 'day-1',
          name: 'Arrival at Charles de Gaulle Airport',
          time: '10:00',
          description: 'Arrive in Paris and transfer to hotel',
          location: 'Charles de Gaulle Airport',
          cost: 0,
          currency: 'EUR',
          category: 'transport',
          icon: 'airplane',
          created_at: '2025-04-20T10:30:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
          votes: [
            {
              id: 'vote-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-21T08:30:00Z',
            },
          ],
          ActivityComment: [
            {
              id: 'comment-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              text: 'Should we pre-book the airport transfer?',
              created_at: '2025-04-21T09:15:00Z',
              user_name: 'Sarah',
              user_avatar: 'https://example.com/avatars/sarah.jpg',
            },
            {
              id: 'comment-2',
              user_id: 'user-789',
              activity_id: 'activity-1',
              text: 'Theres a direct train from CDG to central Paris that might be cheaper',
              created_at: '2025-04-21T10:30:00Z',
              user_name: 'Mike',
              user_avatar: 'https://example.com/avatars/mike.jpg',
            },
          ],
        },
        {
          id: 'activity-2',
          day_id: 'day-1',
          name: 'Check-in at Hotel',
          time: '13:00',
          description: 'Check in at your boutique hotel in Le Marais district',
          location: 'Le Marais',
          cost: 0,
          currency: 'EUR',
          category: 'accommodation',
          icon: 'hotel',
          created_at: '2025-04-20T10:30:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
          votes: [
            {
              id: 'vote-2',
              user_id: 'user-789',
              activity_id: 'activity-2',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-22T10:15:00Z',
            },
            {
              id: 'vote-3',
              user_id: 'user-456',
              activity_id: 'activity-2',
              vote_type: VoteType.Downvote,
              created_at: '2025-04-23T14:20:00Z',
            },
          ],
          ActivityComment: [
            {
              id: 'comment-3',
              user_id: 'user-123',
              activity_id: 'activity-2',
              text: 'The hotel allows early check-in for an extra €20',
              created_at: '2025-04-22T11:00:00Z',
              user_name: 'John',
              user_avatar: 'https://example.com/avatars/john.jpg',
            },
          ],
        },
      ],
    },
    {
      id: 'day-2',
      itinerary_id: 'mock-itinerary-123',
      day_number: 2,
      date: '2025-06-16',
      created_at: '2025-04-20T10:30:00Z',
      activities: [
        {
          id: 'activity-3',
          day_id: 'day-2',
          name: 'Eiffel Tower Visit',
          time: '10:00',
          description: 'Visit the iconic Eiffel Tower',
          location: 'Champ de Mars',
          cost: 25,
          currency: 'EUR',
          category: 'sightseeing',
          icon: 'monument',
          created_at: '2025-04-20T10:30:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
          votes: [
            {
              id: 'vote-4',
              user_id: 'user-123',
              activity_id: 'activity-3',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-24T09:45:00Z',
            },
          ],
          ActivityComment: [
            {
              id: 'comment-4',
              user_id: 'user-456',
              activity_id: 'activity-3',
              text: 'Book tickets in advance to skip the line!',
              created_at: '2025-04-25T08:30:00Z',
              user_name: 'Sarah',
              user_avatar: 'https://example.com/avatars/sarah.jpg',
            },
            {
              id: 'comment-5',
              user_id: 'user-789',
              activity_id: 'activity-3',
              text: 'The summit access is worth the extra cost',
              created_at: '2025-04-25T09:15:00Z',
              user_name: 'Mike',
              user_avatar: 'https://example.com/avatars/mike.jpg',
            },
          ],
        },
      ],
    },
  ],

  // Shared users
  shared_users: [
    {
      id: 'shared-1',
      user_id: 'user-456',
      itinerary_id: 'mock-itinerary-123',
      user_email: 'friend@example.com',
      permission: PermissionType.View,
      created_at: '2025-04-22T08:45:00Z',
      user_name: 'Travel Buddy',
    },
  ],
};
// Tokyo itinerary
export const tokyoItinerary: TripItinerary = {
  id: 'mock-itinerary-tokyo',
  title: 'Tokyo Adventure',
  description: 'Exploring the vibrant metropolis of Tokyo',
  image_url: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc',
  total_cost: 2500,
  currency: 'USD',
  user_id: 'user-123',
  start_date: '2025-07-10',
  end_date: '2025-07-17',
  created_at: '2025-05-01T14:30:00Z',
  updated_at: '2025-05-02T09:15:00Z',
  city: 'Tokyo',
  location: 'Japan',
  tags: ['modern', 'cultural', 'shopping', 'food'],
  rating: 4.9,
  price_level: PriceLevel.Luxury,
  coordinates: {
    lat: 35.6762,
    lng: 139.6503,
  },
  is_featured: true,
  category: 'city',
  is_bookmarked: true,
  is_shared: false,
  is_public: true,
  is_private: false,
  is_completed: false,
  is_favorite: true,

  // Weather information
  weather: [
    {
      id: 'weather-tokyo-1',
      itinerary_id: 'mock-itinerary-tokyo',
      day: 1,
      date: '2025-07-10',
      condition: 'Hot and Humid',
      high_temp: 32,
      low_temp: 25,
      icon: 'weather-sunny-alert',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'weather-tokyo-2',
      itinerary_id: 'mock-itinerary-tokyo',
      day: 2,
      date: '2025-07-11',
      condition: 'Rainy',
      high_temp: 28,
      low_temp: 24,
      icon: 'weather-rainy',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'weather-tokyo-3',
      itinerary_id: 'mock-itinerary-tokyo',
      day: 3,
      date: '2025-07-12',
      condition: 'Sunny',
      high_temp: 31,
      low_temp: 25,
      icon: 'weather-sunny',
      created_at: '2025-05-01T14:30:00Z',
    },
  ],

  weather_overview: {
    id: 'weather-overview-tokyo',
    itinerary_id: 'mock-itinerary-tokyo',
    description:
      'Tokyo will be hot and humid during your visit, with occasional rain showers. Pack light clothing and a small umbrella.',
    recommendations: [
      {
        id: 'weather-rec-tokyo-1',
        weather_overview_id: 'weather-overview-tokyo',
        text: 'Pack breathable, light clothing',
        icon: 'tshirt-crew',
        created_at: '2025-05-01T14:30:00Z',
      },
      {
        id: 'weather-rec-tokyo-2',
        weather_overview_id: 'weather-overview-tokyo',
        text: 'Bring a portable umbrella',
        icon: 'umbrella',
        created_at: '2025-05-01T14:30:00Z',
      },
      {
        id: 'weather-rec-tokyo-3',
        weather_overview_id: 'weather-overview-tokyo',
        text: 'Consider a cooling towel',
        icon: 'rug',
        created_at: '2025-05-01T14:30:00Z',
      },
    ],
    created_at: '2025-05-01T14:30:00Z',
  },

  // Warnings
  warnings: [
    {
      id: 'warning-tokyo-1',
      itinerary_id: 'mock-itinerary-tokyo',
      title: 'Language Barrier',
      description:
        'English is not widely spoken outside of major tourist areas. Consider a translation app.',
      severity: WarningSeverity.Medium,
      icon: 'translate',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'warning-tokyo-2',
      itinerary_id: 'mock-itinerary-tokyo',
      title: 'Rush Hour Crowds',
      description:
        'Avoid using the metro during rush hour (7:30-9:00 AM and 5:30-7:30 PM) if possible.',
      severity: WarningSeverity.Medium,
      icon: 'crowd',
      created_at: '2025-05-01T14:30:00Z',
    },
  ],

  // Packing recommendations
  packing_recommendation: [
    {
      id: 'packing-tokyo-1',
      itinerary_id: 'mock-itinerary-tokyo',
      name: 'Portable Wi-Fi or SIM card',
      category: 'electronics',
      essential: true,
      icon: 'wifi',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'packing-tokyo-2',
      itinerary_id: 'mock-itinerary-tokyo',
      name: 'Comfortable walking shoes',
      category: 'clothing',
      essential: true,
      icon: 'shoe-sneaker',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'packing-tokyo-3',
      itinerary_id: 'mock-itinerary-tokyo',
      name: 'Portable umbrella',
      category: 'accessories',
      essential: true,
      icon: 'umbrella',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'packing-tokyo-4',
      itinerary_id: 'mock-itinerary-tokyo',
      name: 'Translation app',
      category: 'electronics',
      essential: false,
      icon: 'phone',
      created_at: '2025-05-01T14:30:00Z',
    },
  ],

  // General tips
  general_tips: [
    {
      id: 'tip-tokyo-1',
      itinerary_id: 'mock-itinerary-tokyo',
      title: 'Suica/Pasmo Card',
      description: 'Get a rechargeable IC card for easy payment on public transport and in stores.',
      icon: 'card',
      category: 'transport',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'tip-tokyo-2',
      itinerary_id: 'mock-itinerary-tokyo',
      title: 'Convenience Stores',
      description:
        '7-Eleven, Lawson, and FamilyMart are perfect for quick meals, ATMs, and essentials.',
      icon: 'store',
      category: 'food',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'tip-tokyo-3',
      itinerary_id: 'mock-itinerary-tokyo',
      title: 'Vending Machines',
      description: 'Vending machines are everywhere and offer a wide variety of drinks.',
      icon: 'glass-cocktail',
      category: 'convenience',
      created_at: '2025-05-01T14:30:00Z',
    },
  ],

  // Trip highlights
  trip_highlights: [
    {
      id: 'highlight-tokyo-1',
      itinerary_id: 'mock-itinerary-tokyo',
      title: 'Shibuya Crossing',
      description: 'Experience the famous scramble crossing, busiest in the world.',
      icon: 'crossing',
      created_at: '2025-05-01T14:30:00Z',
    },
    {
      id: 'highlight-tokyo-2',
      itinerary_id: 'mock-itinerary-tokyo',
      title: 'Sensō-ji Temple',
      description: "Tokyo's oldest temple, located in Asakusa.",
      icon: 'temple',
      created_at: '2025-05-01T14:30:00Z',
    },
  ],

  // Days and activities
  days: [
    {
      id: 'day-tokyo-1',
      itinerary_id: 'mock-itinerary-tokyo',
      day_number: 1,
      date: '2025-07-10',
      created_at: '2025-05-01T14:30:00Z',
      activities: [
        {
          id: 'activity-tokyo-1',
          day_id: 'day-tokyo-1',
          name: 'Arrive at Narita Airport',
          time: '14:00',
          description: 'Arrive in Tokyo and take the Narita Express to the city',
          location: 'Narita International Airport',
          cost: 3000,
          currency: 'JPY',
          category: 'transport',
          icon: 'airplane',
          created_at: '2025-05-01T14:30:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
          votes: [
            {
              id: 'vote-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-21T08:30:00Z',
            },
          ],
          ActivityComment: [
            {
              id: 'comment-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              text: 'Should we pre-book the airport transfer?',
              created_at: '2025-04-21T09:15:00Z',
              user_name: 'Sarah',
              user_avatar: 'https://example.com/avatars/sarah.jpg',
            },
            {
              id: 'comment-2',
              user_id: 'user-789',
              activity_id: 'activity-1',
              text: 'Theres a direct train from CDG to central Paris that might be cheaper',
              created_at: '2025-04-21T10:30:00Z',
              user_name: 'Mike',
              user_avatar: 'https://example.com/avatars/mike.jpg',
            },
          ],
        },
        {
          id: 'activity-tokyo-2',
          day_id: 'day-tokyo-1',
          name: 'Check-in at Hotel',
          time: '17:00',
          description: 'Check in at your hotel in Shinjuku',
          location: 'Shinjuku',
          cost: 0,
          currency: 'JPY',
          category: 'accommodation',
          icon: 'hotel',
          created_at: '2025-05-01T14:30:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
          votes: [
            {
              id: 'vote-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-21T08:30:00Z',
            },
          ],
          ActivityComment: [],
        },
      ],
    },
    {
      id: 'day-tokyo-2',
      itinerary_id: 'mock-itinerary-tokyo',
      day_number: 2,
      date: '2025-07-11',
      created_at: '2025-05-01T14:30:00Z',
      activities: [
        {
          id: 'activity-tokyo-3',
          day_id: 'day-tokyo-2',
          name: 'Tsukiji Outer Market',
          time: '08:00',
          description: 'Visit the famous fish market and enjoy fresh sushi for breakfast',
          location: 'Tsukiji',
          cost: 3000,
          currency: 'JPY',
          category: 'food',
          icon: 'food',
          created_at: '2025-05-01T14:30:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
          votes: [
            {
              id: 'vote-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-21T08:30:00Z',
            },
          ],
          ActivityComment: [
            {
              id: 'comment-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              text: 'Should we pre-book the airport transfer?',
              created_at: '2025-04-21T09:15:00Z',
              user_name: 'Sarah',
              user_avatar: 'https://example.com/avatars/sarah.jpg',
            },
            {
              id: 'comment-2',
              user_id: 'user-789',
              activity_id: 'activity-1',
              text: 'Theres a direct train from CDG to central Paris that might be cheaper',
              created_at: '2025-04-21T10:30:00Z',
              user_name: 'Mike',
              user_avatar: 'https://example.com/avatars/mike.jpg',
            },
          ],
        },
      ],
    },
  ],

  shared_users: [
    {
      id: 'shared-rome-1',
      user_id: 'user-456',
      itinerary_id: 'mock-itinerary-rome',
      user_email: 'travel-buddy@example.com',
      permission: PermissionType.Edit,
      created_at: '2025-05-04T09:30:00Z',
      user_name: 'Travel Buddy',
    },
  ],
};

// Rome itinerary
export const romeItinerary: TripItinerary = {
  id: 'mock-itinerary-rome',
  title: 'Roman Holiday',
  description: 'Exploring ancient history and modern charm in the Eternal City',
  image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
  total_cost: 1800,
  currency: 'EUR',
  user_id: 'user-123',
  start_date: '2025-09-05',
  end_date: '2025-09-12',
  created_at: '2025-05-03T11:20:00Z',
  updated_at: '2025-05-04T16:45:00Z',
  city: 'Rome',
  location: 'Italy',
  tags: ['historic', 'cultural', 'culinary', 'ancient'],
  rating: 4.7,
  price_level: PriceLevel.Moderate,
  coordinates: {
    lat: 41.9028,
    lng: 12.4964,
  },
  is_featured: false,
  category: 'city',
  is_bookmarked: false,
  is_shared: true,
  is_public: true,
  is_private: false,
  is_completed: false,
  is_favorite: false,

  // Weather information
  weather: [
    {
      id: 'weather-rome-1',
      itinerary_id: 'mock-itinerary-rome',
      day: 1,
      date: '2025-09-05',
      condition: 'Sunny',
      high_temp: 29,
      low_temp: 21,
      icon: 'weather-sunny',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'weather-rome-2',
      itinerary_id: 'mock-itinerary-rome',
      day: 2,
      date: '2025-09-06',
      condition: 'Sunny',
      high_temp: 30,
      low_temp: 22,
      icon: 'weather-sunny',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'weather-rome-3',
      itinerary_id: 'mock-itinerary-rome',
      day: 3,
      date: '2025-09-07',
      condition: 'Partly Cloudy',
      high_temp: 28,
      low_temp: 20,
      icon: 'weather-partly-cloudy',
      created_at: '2025-05-03T11:20:00Z',
    },
  ],

  weather_overview: {
    id: 'weather-overview-rome',
    itinerary_id: 'mock-itinerary-rome',
    description:
      'Rome will be warm and sunny in early September. Expect comfortable evenings but hot afternoons.',
    recommendations: [
      {
        id: 'weather-rec-rome-1',
        weather_overview_id: 'weather-overview-rome',
        text: 'Sun protection is essential',
        icon: 'sun-wireless',
        created_at: '2025-05-03T11:20:00Z',
      },
      {
        id: 'weather-rec-rome-2',
        weather_overview_id: 'weather-overview-rome',
        text: 'Bring a light layer for evenings',
        icon: 'umbrella',
        created_at: '2025-05-03T11:20:00Z',
      },
      {
        id: 'weather-rec-rome-3',
        weather_overview_id: 'weather-overview-rome',
        text: 'Stay hydrated throughout the day',
        icon: 'bottle-soda-classic-outline',
        created_at: '2025-05-03T11:20:00Z',
      },
    ],
    created_at: '2025-05-03T11:20:00Z',
  },

  // Warnings
  warnings: [
    {
      id: 'warning-rome-1',
      itinerary_id: 'mock-itinerary-rome',
      title: 'Pickpocketing',
      description:
        'Be aware of pickpockets in crowded tourist areas, especially around the Colosseum and on public transport.',
      severity: WarningSeverity.Medium,
      icon: 'alert',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'warning-rome-2',
      itinerary_id: 'mock-itinerary-rome',
      title: 'Tourist Areas Closing Times',
      description: 'Most historical sites close by 7:30 PM. Plan your visits accordingly.',
      severity: WarningSeverity.Low,
      icon: 'clock',
      created_at: '2025-05-03T11:20:00Z',
    },
  ],

  // Packing recommendations
  packing_recommendation: [
    {
      id: 'packing-rome-1',
      itinerary_id: 'mock-itinerary-rome',
      name: 'Modest clothing for Vatican visits',
      category: 'clothing',
      essential: true,
      icon: 'tshirt-crew',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'packing-rome-2',
      itinerary_id: 'mock-itinerary-rome',
      name: 'Comfortable walking shoes',
      category: 'clothing',
      essential: true,
      icon: 'shoe-sneaker',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'packing-rome-3',
      itinerary_id: 'mock-itinerary-rome',
      name: 'Water bottle',
      category: 'accessories',
      essential: true,
      icon: 'bottle-soda-classic-outline',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'packing-rome-4',
      itinerary_id: 'mock-itinerary-rome',
      name: 'Sun hat',
      category: 'accessories',
      essential: false,
      icon: 'hat-fedora',
      created_at: '2025-05-03T11:20:00Z',
    },
  ],

  // General tips
  general_tips: [
    {
      id: 'tip-rome-1',
      itinerary_id: 'mock-itinerary-rome',
      title: 'Water Fountains',
      description:
        "Rome has many 'nasoni' (drinking fountains) throughout the city. The water is safe and refreshing.",
      icon: 'fountain',
      category: 'practical',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'tip-rome-2',
      itinerary_id: 'mock-itinerary-rome',
      title: 'Roma Pass',
      description:
        'Consider buying a Roma Pass for free entry to 1-2 museums and unlimited public transport.',
      icon: 'ticket',
      category: 'savings',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'tip-rome-3',
      itinerary_id: 'mock-itinerary-rome',
      title: 'Siesta Hours',
      description: 'Many small shops close from 1-4 PM. Plan your shopping accordingly.',
      icon: 'clock',
      category: 'culture',
      created_at: '2025-05-03T11:20:00Z',
    },
  ],

  // Trip highlights
  trip_highlights: [
    {
      id: 'highlight-rome-1',
      itinerary_id: 'mock-itinerary-rome',
      title: 'Colosseum',
      description: "Visit Rome's iconic ancient amphitheater.",
      icon: 'colosseum',
      created_at: '2025-05-03T11:20:00Z',
    },
    {
      id: 'highlight-rome-2',
      itinerary_id: 'mock-itinerary-rome',
      title: 'Vatican Museums',
      description: 'Home to masterpieces including the Sistine Chapel.',
      icon: 'museum',
      created_at: '2025-05-03T11:20:00Z',
    },
  ],

  // Days and activities
  days: [
    {
      id: 'day-rome-1',
      itinerary_id: 'mock-itinerary-rome',
      day_number: 1,
      date: '2025-09-05',
      created_at: '2025-05-03T11:20:00Z',
      activities: [
        {
          id: 'activity-rome-1',
          day_id: 'day-rome-1',
          name: 'Arrive at Fiumicino Airport',
          time: '11:00',
          description: 'Arrive in Rome and take the Leonardo Express to Roma Termini',
          location: 'Leonardo da Vinci International Airport',
          cost: 14,
          currency: 'EUR',
          category: 'transport',
          icon: 'airplane',
          created_at: '2025-05-03T11:20:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
          votes: [
            {
              id: 'vote-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-21T08:30:00Z',
            },
          ],
          ActivityComment: [
            {
              id: 'comment-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              text: 'Should we pre-book the airport transfer?',
              created_at: '2025-04-21T09:15:00Z',
              user_name: 'Sarah',
              user_avatar: 'https://example.com/avatars/sarah.jpg',
            },
            {
              id: 'comment-2',
              user_id: 'user-789',
              activity_id: 'activity-1',
              text: 'Theres a direct train from CDG to central Paris that might be cheaper',
              created_at: '2025-04-21T10:30:00Z',
              user_name: 'Mike',
              user_avatar: 'https://example.com/avatars/mike.jpg',
            },
          ],
        },
        {
          id: 'activity-rome-2',
          day_id: 'day-rome-1',
          name: 'Check-in at Hotel',
          time: '14:00',
          description: 'Check in at your hotel near the Spanish Steps',
          location: 'Centro Storico',
          cost: 0,
          currency: 'EUR',
          category: 'accommodation',
          icon: 'hotel',
          created_at: '2025-05-03T11:20:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',

          votes: [
            {
              id: 'vote-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-21T08:30:00Z',
            },
          ],
          ActivityComment: [
            {
              id: 'comment-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              text: 'Should we pre-book the airport transfer?',
              created_at: '2025-04-21T09:15:00Z',
              user_name: 'Sarah',
              user_avatar: 'https://example.com/avatars/sarah.jpg',
            },
            {
              id: 'comment-2',
              user_id: 'user-789',
              activity_id: 'activity-1',
              text: 'Theres a direct train from CDG to central Paris that might be cheaper',
              created_at: '2025-04-21T10:30:00Z',
              user_name: 'Mike',
              user_avatar: 'https://example.com/avatars/mike.jpg',
            },
          ],
        },
      ],
    },
    {
      id: 'day-rome-2',
      itinerary_id: 'mock-itinerary-rome',
      day_number: 2,
      date: '2025-09-06',
      created_at: '2025-05-03T11:20:00Z',
      activities: [
        {
          id: 'activity-rome-3',
          day_id: 'day-rome-2',
          name: 'Colosseum & Roman Forum',
          time: '09:00',
          description: 'Guided tour of the Colosseum and Roman Forum',
          location: 'Colosseum',
          cost: 60,
          currency: 'EUR',
          category: 'sightseeing',
          icon: 'monument',
          created_at: '2025-05-03T11:20:00Z',
          image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
          votes: [
            {
              id: 'vote-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              vote_type: VoteType.Upvote,
              created_at: '2025-04-21T08:30:00Z',
            },
          ],
          ActivityComment: [
            {
              id: 'comment-1',
              user_id: 'user-456',
              activity_id: 'activity-1',
              text: 'Should we pre-book the airport transfer?',
              created_at: '2025-04-21T09:15:00Z',
              user_name: 'Sarah',
              user_avatar: 'https://example.com/avatars/sarah.jpg',
            },
            {
              id: 'comment-2',
              user_id: 'user-789',
              activity_id: 'activity-1',
              text: 'Theres a direct train from CDG to central Paris that might be cheaper',
              created_at: '2025-04-21T10:30:00Z',
              user_name: 'Mike',
              user_avatar: 'https://example.com/avatars/mike.jpg',
            },
          ],
        },
      ],
    },
  ],

  shared_users: [
    {
      id: 'shared-rome-1',
      user_id: 'user-456',
      itinerary_id: 'mock-itinerary-rome',
      user_email: 'travel-buddy@example.com',
      permission: PermissionType.Edit,
      created_at: '2025-05-04T09:30:00Z',
      user_name: 'Travel Buddy',
    },
  ],
};

// Export an array of all mock itineraries for easy access
export const mockItineraries: TripItinerary[] = [parisItinerary, tokyoItinerary, romeItinerary];

// Empty itinerary for loading/error states testing
export const emptyItinerary: TripItinerary = {
  id: '',
  title: '',
  description: '',
  image_url: '',
  total_cost: 0,
  currency: 'USD',
  user_id: '',
  start_date: '',
  end_date: '',
  created_at: '',
  updated_at: '',
  city: '',
  location: '',
  tags: [],
  rating: 0,
  price_level: PriceLevel.Luxury,
  coordinates: {
    lat: 0,
    lng: 0,
  },
  is_featured: false,
  category: '',
  is_bookmarked: false,
  is_shared: false,
  is_public: false,
  is_private: false,
  is_completed: false,
  weather: [],
  weather_overview: {
    id: '',
    itinerary_id: '',
    description: '',
    recommendations: [],
  },
  warnings: [],
  packing_recommendation: [],
  general_tips: [],
  trip_highlights: [],
  days: [
    {
      id: '',
      itinerary_id: '',
      day_number: 0,
      date: '',
      created_at: '',
      activities: [
        {
          id: '',
          day_id: '',
          name: '',
          time: '',
          description: '',
          location: '',
          cost: 0,
          currency: '',
          category: '',
          icon: '',
          created_at: '',
          votes: [],
          ActivityComment: [],
        },
      ],
    },
  ],
  shared_users: [],
};
